"""resource requisitions header

Revision ID: 1b5f916b2980
Revises: 6fbd3fd97bf3
Create Date: 2026-01-19 16:55:32.876458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b5f916b2980'
down_revision: Union[str, Sequence[str], None] = '6fbd3fd97bf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requisitions',
    sa.Column('req_id', sa.Integer(), nullable=False),
    sa.Column('raised_by', sa.Integer(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('client_name', sa.String(length=100), nullable=True),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=10), nullable=True),
    sa.Column('budget', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('budget_approved', sa.Boolean(), nullable=True),
    sa.Column('required_by', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("priority IN ('High', 'Medium', 'Low')", name='chk_requisition_priority'),
    sa.CheckConstraint("status IN ('Open', 'In Progress', 'Closed', 'Cancelled')", name='chk_requisition_status'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['raised_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('req_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requisitions')
    # ### end Alembic commands ###
