"""employee financial data

Revision ID: 2b873237dd87
Revises: de1e13577cd9
Create Date: 2026-01-19 16:45:37.527570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b873237dd87'
down_revision: Union[str, Sequence[str], None] = 'de1e13577cd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_finance',
    sa.Column('emp_id', sa.String(length=20), nullable=False),
    sa.Column('bank_details_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('tax_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['emp_id'], ['employees.emp_id'], ),
    sa.PrimaryKeyConstraint('emp_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee_finance')
    # ### end Alembic commands ###
