"""schema_sync_check

Revision ID: 42c538a9ab8e
Revises: e754d5404f22
Create Date: 2026-02-05 13:44:13.392298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42c538a9ab8e'
down_revision: Union[str, Sequence[str], None] = 'e754d5404f22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_company_roles_role_id'), 'company_roles', ['role_id'], unique=False)
    op.create_unique_constraint('uq_company_roles_role_name', 'company_roles', ['role_name'])
    op.drop_constraint(op.f('fk_employees_company_role'), 'employees', type_='foreignkey')
    op.create_foreign_key(None, 'employees', 'company_roles', ['company_role_id'], ['role_id'])
    op.add_column('requisition_items', sa.Column('assigned_ta', sa.Integer(), nullable=True))
    op.drop_index(op.f('idx_requisition_items_assigned_ta'), table_name='requisition_items')
    op.drop_index(op.f('idx_requisition_items_status'), table_name='requisition_items')
    op.drop_index(op.f('idx_requisition_items_unassigned'), table_name='requisition_items', postgresql_where='(assigned_ta_id IS NULL)')
    op.create_index(op.f('ix_requisition_items_assigned_ta'), 'requisition_items', ['assigned_ta'], unique=False)
    op.create_index(op.f('ix_requisition_items_item_status'), 'requisition_items', ['item_status'], unique=False)
    op.create_index(op.f('ix_requisition_items_req_id'), 'requisition_items', ['req_id'], unique=False)
    op.drop_constraint(op.f('fk_requisition_items_assigned_ta'), 'requisition_items', type_='foreignkey')
    op.drop_constraint(op.f('requisition_items_req_id_fkey'), 'requisition_items', type_='foreignkey')
    op.drop_constraint(op.f('requisition_items_assigned_emp_id_fkey'), 'requisition_items', type_='foreignkey')
    op.create_foreign_key(None, 'requisition_items', 'requisitions', ['req_id'], ['req_id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'requisition_items', 'users', ['assigned_ta'], ['user_id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'requisition_items', 'employees', ['assigned_emp_id'], ['emp_id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'requisition_items', 'employees', ['replaced_emp_id'], ['emp_id'], ondelete='RESTRICT')
    op.drop_column('requisition_items', 'assigned_ta_id')
    op.create_index(op.f('ix_requisitions_overall_status'), 'requisitions', ['overall_status'], unique=False)
    op.drop_constraint(op.f('requisitions_raised_by_fkey'), 'requisitions', type_='foreignkey')
    op.drop_constraint(op.f('requisitions_budget_approved_by_fkey'), 'requisitions', type_='foreignkey')
    op.drop_constraint(op.f('requisitions_approved_by_fkey'), 'requisitions', type_='foreignkey')
    op.drop_constraint(op.f('requisitions_assigned_ta_fkey'), 'requisitions', type_='foreignkey')
    op.create_foreign_key(None, 'requisitions', 'users', ['budget_approved_by'], ['user_id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'requisitions', 'users', ['raised_by'], ['user_id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'requisitions', 'users', ['assigned_ta'], ['user_id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'requisitions', 'users', ['approved_by'], ['user_id'], ondelete='RESTRICT')
    op.drop_column('requisitions', 'fulfilled_items')
    op.drop_column('requisitions', 'active_items')
    op.drop_column('requisitions', 'total_items')
    op.add_column('skills', sa.Column('normalized_name', sa.String(length=50), nullable=False, server_default=""))
    op.add_column('skills', sa.Column('is_verified', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('skills', sa.Column('created_by', sa.Integer(), nullable=True))
    op.execute("UPDATE skills SET normalized_name = LOWER(TRIM(skill_name)) WHERE normalized_name = ''")
    op.alter_column('skills', 'normalized_name', server_default=None)
    op.create_unique_constraint('uq_skills_normalized_name', 'skills', ['normalized_name'])
    op.create_foreign_key(None, 'skills', 'users', ['created_by'], ['user_id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'skills', type_='foreignkey')
    op.drop_constraint(None, 'skills', type_='unique')
    op.drop_column('skills', 'created_by')
    op.drop_column('skills', 'is_verified')
    op.drop_column('skills', 'normalized_name')
    op.add_column('requisitions', sa.Column('total_items', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('requisitions', sa.Column('active_items', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('requisitions', sa.Column('fulfilled_items', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'requisitions', type_='foreignkey')
    op.drop_constraint(None, 'requisitions', type_='foreignkey')
    op.drop_constraint(None, 'requisitions', type_='foreignkey')
    op.drop_constraint(None, 'requisitions', type_='foreignkey')
    op.create_foreign_key(op.f('requisitions_assigned_ta_fkey'), 'requisitions', 'users', ['assigned_ta'], ['user_id'])
    op.create_foreign_key(op.f('requisitions_approved_by_fkey'), 'requisitions', 'users', ['approved_by'], ['user_id'])
    op.create_foreign_key(op.f('requisitions_budget_approved_by_fkey'), 'requisitions', 'users', ['budget_approved_by'], ['user_id'])
    op.create_foreign_key(op.f('requisitions_raised_by_fkey'), 'requisitions', 'users', ['raised_by'], ['user_id'])
    op.drop_index(op.f('ix_requisitions_overall_status'), table_name='requisitions')
    op.add_column('requisition_items', sa.Column('assigned_ta_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'requisition_items', type_='foreignkey')
    op.drop_constraint(None, 'requisition_items', type_='foreignkey')
    op.drop_constraint(None, 'requisition_items', type_='foreignkey')
    op.drop_constraint(None, 'requisition_items', type_='foreignkey')
    op.create_foreign_key(op.f('requisition_items_assigned_emp_id_fkey'), 'requisition_items', 'employees', ['assigned_emp_id'], ['emp_id'])
    op.create_foreign_key(op.f('requisition_items_req_id_fkey'), 'requisition_items', 'requisitions', ['req_id'], ['req_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_requisition_items_assigned_ta'), 'requisition_items', 'users', ['assigned_ta_id'], ['user_id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_requisition_items_req_id'), table_name='requisition_items')
    op.drop_index(op.f('ix_requisition_items_item_status'), table_name='requisition_items')
    op.drop_index(op.f('ix_requisition_items_assigned_ta'), table_name='requisition_items')
    op.create_index(op.f('idx_requisition_items_unassigned'), 'requisition_items', ['req_id'], unique=False, postgresql_where='(assigned_ta_id IS NULL)')
    op.create_index(op.f('idx_requisition_items_status'), 'requisition_items', ['item_status'], unique=False)
    op.create_index(op.f('idx_requisition_items_assigned_ta'), 'requisition_items', ['assigned_ta_id'], unique=False)
    op.drop_column('requisition_items', 'assigned_ta')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.create_foreign_key(op.f('fk_employees_company_role'), 'employees', 'company_roles', ['company_role_id'], ['role_id'], ondelete='SET NULL')
    op.drop_constraint('uq_company_roles_role_name', 'company_roles', type_='unique')
    op.drop_index(op.f('ix_company_roles_role_id'), table_name='company_roles')
    # ### end Alembic commands ###
