"""organizational structure tables

Revision ID: 460a649a602f
Revises: d25c90c27387
Create Date: 2026-01-19 16:30:56.701839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '460a649a602f'
down_revision: Union[str, Sequence[str], None] = 'd25c90c27387'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('department_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('department_id'),
    sa.UniqueConstraint('department_name')
    )
    op.create_table('locations',
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('location_id')
    )
    op.create_table('employee_assignments',
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('emp_id', sa.String(length=20), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.String(length=20), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.department_id'], ),
    sa.ForeignKeyConstraint(['emp_id'], ['employees.emp_id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.location_id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['employees.emp_id'], ),
    sa.PrimaryKeyConstraint('assignment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee_assignments')
    op.drop_table('locations')
    op.drop_table('departments')
    # ### end Alembic commands ###
