"""employee availability tracking

Revision ID: 6fbd3fd97bf3
Revises: 2b873237dd87
Create Date: 2026-01-19 16:51:48.880497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fbd3fd97bf3'
down_revision: Union[str, Sequence[str], None] = '2b873237dd87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_availability',
    sa.Column('emp_id', sa.String(length=20), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('availability_pct', sa.Integer(), nullable=False),
    sa.CheckConstraint('availability_pct BETWEEN 0 AND 100', name='chk_availability_pct'),
    sa.ForeignKeyConstraint(['emp_id'], ['employees.emp_id'], ),
    sa.PrimaryKeyConstraint('emp_id', 'effective_from')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee_availability')
    # ### end Alembic commands ###
