"""employee contact information

Revision ID: 9dbfe6d5be61
Revises: 460a649a602f
Create Date: 2026-01-19 16:36:54.964469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dbfe6d5be61'
down_revision: Union[str, Sequence[str], None] = '460a649a602f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_contacts',
    sa.Column('emp_id', sa.String(length=20), nullable=False),
    sa.Column('contact_type', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.CheckConstraint("contact_type IN ('Work', 'Personal', 'Emergency')", name='chk_contact_type'),
    sa.ForeignKeyConstraint(['emp_id'], ['employees.emp_id'], ),
    sa.PrimaryKeyConstraint('emp_id', 'contact_type')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee_contacts')
    # ### end Alembic commands ###
