"""employee core table

Revision ID: d25c90c27387
Revises: 08fb9d6ffd44
Create Date: 2026-01-19 16:16:04.791778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd25c90c27387'
down_revision: Union[str, Sequence[str], None] = '08fb9d6ffd44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('emp_id', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('rbm_email', sa.String(length=100), nullable=False),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('doj', sa.Date(), nullable=True),
    sa.Column('emp_status', sa.String(length=20), server_default='Active', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("emp_status IN ('Active', 'On Leave', 'Exited')", name='chk_emp_status'),
    sa.PrimaryKeyConstraint('emp_id'),
    sa.UniqueConstraint('rbm_email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employees')
    # ### end Alembic commands ###
