"""requisition line items

Revision ID: d6b93ec4b0d4
Revises: 1b5f916b2980
Create Date: 2026-01-19 16:59:14.173094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6b93ec4b0d4'
down_revision: Union[str, Sequence[str], None] = '1b5f916b2980'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requisition_items',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('req_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.Column('required_level', sa.String(length=20), nullable=True),
    sa.Column('education_requirement', sa.String(length=100), nullable=True),
    sa.Column('assigned_emp_id', sa.String(length=20), nullable=True),
    sa.Column('item_status', sa.String(length=20), nullable=True),
    sa.CheckConstraint("item_status IN ('Pending', 'Fulfilled', 'Cancelled')", name='chk_requisition_item_status'),
    sa.ForeignKeyConstraint(['assigned_emp_id'], ['employees.emp_id'], ),
    sa.ForeignKeyConstraint(['req_id'], ['requisitions.req_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.skill_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requisition_items')
    # ### end Alembic commands ###
