"""skills and education tables

Revision ID: de1e13577cd9
Revises: 9dbfe6d5be61
Create Date: 2026-01-19 16:42:06.737426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de1e13577cd9'
down_revision: Union[str, Sequence[str], None] = '9dbfe6d5be61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills',
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('skill_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('skill_id'),
    sa.UniqueConstraint('skill_name')
    )
    op.create_table('employee_education',
    sa.Column('edu_id', sa.Integer(), nullable=False),
    sa.Column('emp_id', sa.String(length=20), nullable=False),
    sa.Column('qualification', sa.String(length=100), nullable=True),
    sa.Column('specialization', sa.String(length=100), nullable=True),
    sa.Column('institution', sa.String(length=100), nullable=True),
    sa.Column('year_completed', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['emp_id'], ['employees.emp_id'], ),
    sa.PrimaryKeyConstraint('edu_id')
    )
    op.create_table('employee_skills',
    sa.Column('emp_id', sa.String(length=20), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('proficiency_level', sa.String(length=20), nullable=True),
    sa.Column('years_experience', sa.DECIMAL(precision=4, scale=1), nullable=True),
    sa.ForeignKeyConstraint(['emp_id'], ['employees.emp_id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.skill_id'], ),
    sa.PrimaryKeyConstraint('emp_id', 'skill_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee_skills')
    op.drop_table('employee_education')
    op.drop_table('skills')
    # ### end Alembic commands ###
