"""project schema

Revision ID: a8823a2289fb
Revises: 
Create Date: 2026-03-02 13:09:28.852300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8823a2289fb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('project_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_name', sa.String(length=200), nullable=False),
    sa.Column('client_name', sa.String(length=200), nullable=True),
    sa.Column('project_status', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("project_status IN ('Active', 'On Hold', 'Completed', 'Cancelled')", name='chk_project_status'),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('project_timelines',
    sa.Column('timeline_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('planned_end_date', sa.Date(), nullable=False),
    sa.Column('actual_end_date', sa.Date(), nullable=True),
    sa.Column('planned_start_date', sa.Date(), nullable=True),
    sa.Column('actual_start_date', sa.Date(), nullable=True),
    sa.Column('version_number', sa.Integer(), server_default='1', nullable=False),
    sa.Column('reason_for_change', sa.Text(), nullable=True),
    sa.Column('is_current', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('timeline_id')
    )
    op.create_table('employee_project_assignments',
    sa.Column('assignment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('emp_id', sa.String(length=20), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('allocation_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('billing_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('billing_start_date', sa.Date(), nullable=True),
    sa.Column('billing_end_date', sa.Date(), nullable=True),
    sa.Column('is_billable', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('timesheet_required', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('client_pm_name', sa.String(length=200), nullable=True),
    sa.Column('billing_project_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("status IN ('Planned', 'Active', 'Ended')", name='chk_assignment_status'),
    sa.CheckConstraint('allocation_pct >= 0 AND allocation_pct <= 100', name='chk_allocation_pct'),
    sa.ForeignKeyConstraint(['billing_project_id'], ['projects.project_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['emp_id'], ['employees.emp_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('assignment_id')
    )
    op.create_table('project_managers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('manager_user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('assigned_from', sa.Date(), nullable=False),
    sa.Column('assigned_to', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['manager_user_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_audit_log_entity'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_performed_by'), table_name='audit_log', postgresql_where='(performed_by IS NOT NULL)')
    op.drop_index(op.f('ix_candidates_req_id'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_req_item'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_stage'), table_name='candidates')
    op.create_index(op.f('ix_candidates_current_stage'), 'candidates', ['current_stage'], unique=False)
    op.create_index(op.f('ix_candidates_requisition_id'), 'candidates', ['requisition_id'], unique=False)
    op.create_index(op.f('ix_candidates_requisition_item_id'), 'candidates', ['requisition_item_id'], unique=False)
    op.drop_index(op.f('ix_interviews_candidate'), table_name='interviews')
    op.create_index(op.f('ix_interviews_candidate_id'), 'interviews', ['candidate_id'], unique=False)
    op.drop_index(op.f('ix_req_items_sync_lookup'), table_name='requisition_items')
    op.drop_index(op.f('ix_requisition_items_assigned_emp_id'), table_name='requisition_items', postgresql_where='(assigned_emp_id IS NOT NULL)')
    op.drop_index(op.f('ix_requisition_items_budget_lookup'), table_name='requisition_items')
    op.drop_index(op.f('ix_requisition_items_req_status'), table_name='requisition_items')
    op.alter_column('requisition_status_history', 'old_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('requisition_status_history', 'new_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_index(op.f('ix_req_status_history_req_time'), table_name='requisition_status_history')
    op.alter_column('requisitions', 'budget_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment=None,
               existing_comment='DEPRECATED: Use requisition_items.estimated_budget instead. This column is retained for audit history and backward compatibility. Do NOT use for new code. Budget totals must be computed from items. Deprecated as of migration budget_item_level_refactor (2026-02-12).',
               existing_nullable=True)
    op.drop_index(op.f('ix_requisitions_assigned_ta'), table_name='requisitions', postgresql_where='(assigned_ta IS NOT NULL)')
    op.drop_index(op.f('ix_requisitions_raised_by'), table_name='requisitions')
    op.drop_index(op.f('ix_requisitions_status_created'), table_name='requisitions')
    op.drop_index(op.f('ix_wf_audit_action_entity'), table_name='workflow_transition_audit')
    op.drop_index(op.f('ix_wf_audit_entity_lookup'), table_name='workflow_transition_audit')
    op.drop_index(op.f('ix_wf_audit_time_stats'), table_name='workflow_transition_audit')
    op.drop_index(op.f('ix_wf_audit_user_activity'), table_name='workflow_transition_audit')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_wf_audit_user_activity'), 'workflow_transition_audit', ['performed_by', 'created_at'], unique=False)
    op.create_index(op.f('ix_wf_audit_time_stats'), 'workflow_transition_audit', ['created_at', 'action'], unique=False)
    op.create_index(op.f('ix_wf_audit_entity_lookup'), 'workflow_transition_audit', ['entity_type', 'entity_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_wf_audit_action_entity'), 'workflow_transition_audit', ['action', 'entity_type'], unique=False)
    op.create_index(op.f('ix_requisitions_status_created'), 'requisitions', ['overall_status', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_requisitions_raised_by'), 'requisitions', ['raised_by'], unique=False)
    op.create_index(op.f('ix_requisitions_assigned_ta'), 'requisitions', ['assigned_ta'], unique=False, postgresql_where='(assigned_ta IS NOT NULL)')
    op.alter_column('requisitions', 'budget_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='DEPRECATED: Use requisition_items.estimated_budget instead. This column is retained for audit history and backward compatibility. Do NOT use for new code. Budget totals must be computed from items. Deprecated as of migration budget_item_level_refactor (2026-02-12).',
               existing_nullable=True)
    op.create_index(op.f('ix_req_status_history_req_time'), 'requisition_status_history', ['req_id', sa.literal_column('changed_at DESC')], unique=False)
    op.alter_column('requisition_status_history', 'new_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('requisition_status_history', 'old_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.create_index(op.f('ix_requisition_items_req_status'), 'requisition_items', ['req_id', 'item_status'], unique=False)
    op.create_index(op.f('ix_requisition_items_budget_lookup'), 'requisition_items', ['req_id', 'estimated_budget'], unique=False)
    op.create_index(op.f('ix_requisition_items_assigned_emp_id'), 'requisition_items', ['assigned_emp_id'], unique=False, postgresql_where='(assigned_emp_id IS NOT NULL)')
    op.create_index(op.f('ix_req_items_sync_lookup'), 'requisition_items', ['req_id', 'item_status'], unique=False)
    op.drop_index(op.f('ix_interviews_candidate_id'), table_name='interviews')
    op.create_index(op.f('ix_interviews_candidate'), 'interviews', ['candidate_id'], unique=False)
    op.drop_index(op.f('ix_candidates_requisition_item_id'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_requisition_id'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_current_stage'), table_name='candidates')
    op.create_index(op.f('ix_candidates_stage'), 'candidates', ['current_stage'], unique=False)
    op.create_index(op.f('ix_candidates_req_item'), 'candidates', ['requisition_item_id'], unique=False)
    op.create_index(op.f('ix_candidates_req_id'), 'candidates', ['requisition_id'], unique=False)
    op.create_index(op.f('ix_audit_log_performed_by'), 'audit_log', ['performed_by', sa.literal_column('performed_at DESC')], unique=False, postgresql_where='(performed_by IS NOT NULL)')
    op.create_index(op.f('ix_audit_log_entity'), 'audit_log', ['entity_name', 'entity_id'], unique=False)
    op.drop_table('project_managers')
    op.drop_table('employee_project_assignments')
    op.drop_table('project_timelines')
    op.drop_table('projects')
    # ### end Alembic commands ###
